---
title: "Extracurricular Experience"

---

##INTERNSHIP
**Merck Sharp & Dohme (China) Co., Ltd. **\
*Associate Advisor, Medical Affairs Department*\
*Shanghai,China, 06/2017-09/2017* \
- Learned about publishing processes and major types of medical and clinical research including meta-analysis and epidemiological studies, and got familiar with the according trial processes\
- Arranged kick-off meetings for research design, and coordinated with medical advisors, authors and practitioners to sort out better solutions to research methodology \
- Participated in the publication procedure of DYSIS China sub-analysis, HPV epidemiological review in China, and 9 other cases of publication \
- Optimised the existing standard operating procedures for preparation and publishing so as to conform to the current publication guidelines.
\n\n

##SCHOOL ACTIVITIES
**Mandarin Class, UCL Chinese Students and Scholar Association**\
*Head of Executive Committee*\
*London, UK, 10/2016-06/2018*\
- Responsible for compiling teaching materials and making classroom reservations \
-	Designed flyers for all UCL students on campus about the latest class activities and sent out emails of class schedules to all class members including students and professors on a weekly basis\
-	Organized two major events, “Chinese Cuisine Appreciation” and “Tie a Chinese Knot”, hosting ~30 participants 


